(write-line "Please enter the Paragraph with no \\n :")
(defvar paragraph (read-line))
(write-line "Please enter the key to search :")
(defvar key (read-line))
(write-line "Please enter value to replace :")
(defvar val (read-line))
(defvar flag 0)
(loop for itterator from 0 to (- (length paragraph) (length key))
    do(setq flag 0)
    do(if(> (+ itterator (length key)) (length paragraph))
        (return )
    )
    do(loop for itterator2 from 0 to (- (length key) 1)
        do(if (char/= (char paragraph (+ itterator itterator2)) (char key itterator2))
            (setf flag 1)
        )
    )
    do(if (= flag 0)
        (setf paragraph (concatenate 'string (subseq paragraph 0 itterator) val (subseq paragraph (+ itterator (length key)))))
    )
)
(write paragraph)